services:
  pysr:
    image: pysrimage:latest    
    hostname: pysr-test
    networks:
      - mdk
    deploy:
      mode: replicated
      replicas: 3
    command: [ "sh", "-c",  "python app1.py" ]
    restart: always
    
    
  ngi:
    image: nginximage:latest
    container_name: ngi-test
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    hostname: ngi-test
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mdk

  kong:
    image: registry.inventec/proxy/kong:latest
    user: kong 
    environment:
      - KONG_DATABASE=off #specifies the type of database that stores kong config
      - KONG_DECLARATIVE_CONFIG=/kong/kongconfig.yml
      - KONG_PG_PASSWORD=kongpass #password of postgresql user, need to match postgres_password
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout #redirect logs to standard output stream
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr #redirect logs to linux standard error output stream
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl #bind addr for admin API
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl #specify where the proxy should listen
        #- KONG_PLUGINS=bundled,response-transformer,file-log,connection-limiting,rate-limiting,ip-restriction
    volumes:
      - ./kong/kongconfig.yml:/kong/kongconfig.yml
        # - ./nginx-kong.conf:/nginx-kong.conf  
    ports:
      - "8000:8000"  #kong proxy over http
      - "8443:8443"  #kong proxy over https
      - "8001:8001" #used for admin api over http
      - "8444:8444" #used for admin api over https
    healthcheck:
      test: ["CMD", "kong/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - kong_net
      
  keepalived:
    image: registry.inventec/infra/keepalived:2.0.17
      #    environment: 
      #KEEPALIVED_INTERFACE: "enp0s3"
      #KEEPALIVED_VIRTUAL_IP: "10.0.2.231"
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - "./keepalive/keepalive.conf:/container/service/keepalived/assets/keepalived.conf:ro"
     
    logging:
      driver: 'json-file'
      options:
        max-size: 10m    
    command: --loglevel debug --copy-service
   

networks:
  mdk:
    driver: bridge
  kong_net:
    driver: bridge

